### ISSUE TITLE
 Can not run in clojure 1.8

### ISSUE THREAD

**Issue by xlisp** [anolivetree/gradle-clojure-android-sample#1]
Hi, Hiroshi Sakurai
this is my Android project, fork in your gradle-clojure-android-sample: 
https://github.com/chanshunli/gradle-clojure-android-sample/tree/clojure18000000

I want run it in clojure 1.8, but it can not work(it is compile success), can you help me? 

thanks :-)

**Comment by xlisp** [comment]
hi @anolivetree

**Comment by anolivetree** [comment]
Hi,

Clojure needs to be modified to use dalvik class loader. 1.7 has been
ported to Android but 1.8 has not.

Regards,
Hiroshi

**Comment by xlisp** [comment]
I want update [clojure-android](https://github.com/clojure-android/clojure) to support 1.8, Please tell me what to do next. 
Thanks Hiroshi.

Regards,
Steve Chan
